### ISSUE TITLE
Error Downloading dataset

### ISSUE THREAD

**Issue by geogeek11** [datarevenue-berlin/code-challenge-2020#6] opened 2019-12-04 13:21 UTC
In order the build the images and download the data, I executed ```./build-task-images.sh 0.1```, then I executed ```docker-compose up orchestrator```, but i got this errors:

```sudo docker-compose up orchestrator
WARNING: The PWD variable is not set. Defaulting to a blank string.
Creating code-challenge-2019_luigid_1         ... done
Creating code-challenge-2019_dask-scheduler_1 ... done
Recreating code-challenge-2019_orchestrator_1 ... done
Attaching to code-challenge-2019_orchestrator_1
orchestrator_1    | DEBUG: Checking if DownloadData(no_remove_finished=False, fname=wine_dataset, out_dir=/usr/share/data/raw/, url=https://github.com/datarevenue-berlin/code-challenge-2019/releases/download/0.1.0/dataset_sampled.csv) is complete
orchestrator_1    | INFO: Informed scheduler that task   DownloadData_wine_dataset_False__usr_share_data__79bc385f2e   has status   PENDING
orchestrator_1    | INFO: Done scheduling tasks
orchestrator_1    | INFO: Running Worker with 1 processes
orchestrator_1    | DEBUG: Asking scheduler for work...
orchestrator_1    | DEBUG: Pending tasks: 1
orchestrator_1    | INFO: [pid 1] Worker Worker(salt=005178342, workers=1, host=49f018198416, username=root, pid=1) running   DownloadData(no_remove_finished=False, fname=wine_dataset, out_dir=/usr/share/data/raw/, url=https://github.com/datarevenue-berlin/code-challenge-2019/releases/download/0.1.0/dataset_sampled.csv)
orchestrator_1    | ERROR: [pid 1] Worker Worker(salt=005178342, workers=1, host=49f018198416, username=root, pid=1) failed    DownloadData(no_remove_finished=False, fname=wine_dataset, out_dir=/usr/share/data/raw/, url=https://github.com/datarevenue-berlin/code-challenge-2019/releases/download/0.1.0/dataset_sampled.csv)
orchestrator_1    | Traceback (most recent call last):
orchestrator_1    |   File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
orchestrator_1    |     response.raise_for_status()
orchestrator_1    |   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
orchestrator_1    |     raise HTTPError(http_error_msg, response=self)
orchestrator_1    | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/5ddaa92a0628f808540bcc84316fcb811524fcc25d238cc199a0e707adb5989d/start
orchestrator_1    | 
orchestrator_1    | During handling of the above exception, another exception occurred:
orchestrator_1    | 
orchestrator_1    | Traceback (most recent call last):
orchestrator_1    |   File "/usr/local/lib/python3.6/site-packages/luigi/worker.py", line 199, in run
orchestrator_1    |     new_deps = self._run_get_new_deps()
orchestrator_1    |   File "/usr/local/lib/python3.6/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
orchestrator_1    |     task_gen = self.task.run()
orchestrator_1    |   File "/opt/orchestrator/util.py", line 352, in run
orchestrator_1    |     self._run_and_track_task()
orchestrator_1    |   File "/opt/orchestrator/util.py", line 364, in _run_and_track_task
orchestrator_1    |     self.configuration,
orchestrator_1    |   File "/opt/orchestrator/util.py", line 195, in run_container
orchestrator_1    |     raise e
orchestrator_1    |   File "/opt/orchestrator/util.py", line 185, in run_container
orchestrator_1    |     **configuration)
orchestrator_1    |   File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 809, in run
orchestrator_1    |     container.start()
orchestrator_1    |   File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 400, in start
orchestrator_1    |     return self.client.api.start(self.id, **kwargs)
orchestrator_1    |   File "/usr/local/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
orchestrator_1    |     return f(self, resource_id, *args, **kwargs)
orchestrator_1    |   File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 1095, in start
orchestrator_1    |     self._raise_for_status(res)
orchestrator_1    |   File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
orchestrator_1    |     raise create_api_error_from_http_exception(e)
orchestrator_1    |   File "/usr/local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
orchestrator_1    |     raise cls(e, response=response, explanation=explanation)
orchestrator_1    | docker.errors.NotFound: 404 Client Error: Not Found ("network code_challenge_default not found")
orchestrator_1    | DEBUG: 1 running tasks, waiting for next task to finish
orchestrator_1    | INFO: Informed scheduler that task   DownloadData_wine_dataset_False__usr_share_data__79bc385f2e   has status   FAILED
orchestrator_1    | DEBUG: Asking scheduler for work...
orchestrator_1    | DEBUG: Done
orchestrator_1    | DEBUG: There are no more tasks to run at this time
orchestrator_1    | DEBUG: There are 1 pending tasks possibly being run by other workers
orchestrator_1    | DEBUG: There are 1 pending tasks unique to this worker
orchestrator_1    | DEBUG: There are 1 pending tasks last scheduled by this worker
orchestrator_1    | INFO: Worker Worker(salt=005178342, workers=1, host=49f018198416, username=root, pid=1) was stopped. Shutting down Keep-Alive thread
orchestrator_1    | INFO: 
orchestrator_1    | ===== Luigi Execution Summary =====
orchestrator_1    | 
orchestrator_1    | Scheduled 1 tasks of which:
orchestrator_1    | * 1 failed:
orchestrator_1    |     - 1 DownloadData(no_remove_finished=False, fname=wine_dataset, out_dir=/usr/share/data/raw/, url=https://github.com/datarevenue-berlin/code-challenge-2019/releases/download/0.1.0/dataset_sampled.csv)
orchestrator_1    | 
orchestrator_1    | This progress looks :( because there were failed tasks
orchestrator_1    | 
orchestrator_1    | ===== Luigi Execution Summary =====
orchestrator_1    | 
code-challenge-2019_orchestrator_1 exited with code 0

**Comment by kayibal** [comment] 2020-09-17 06:36
Closing as likely duplicate of #14

**Closed as completed by kayibal** 2020-09-17 06:36 UTC
